var data = {
  images : [
    { active: "active", src: "assets/img/Las Aventuras del Monito/Level1_1.jpg", to: "0" },
    { src: "assets/img/Las Aventuras del Monito/Level1_2.jpg", to: "1" },
    { src: "assets/img/Las Aventuras del Monito/Level1_3.jpg", to: "2" },
    { src: "assets/img/Las Aventuras del Monito/Level1_4.jpg", to: "3" },
    { src: "assets/img/Las Aventuras del Monito/Level2_1.jpg", to: "4" },
    { src: "assets/img/Las Aventuras del Monito/Level2_2.jpg", to: "5" },
    { src: "assets/img/Las Aventuras del Monito/Level2_3.jpg", to: "6" },
    { src: "assets/img/Las Aventuras del Monito/Level2_4.jpg", to: "7" },
    { src: "assets/img/Las Aventuras del Monito/Level2_5.jpg", to: "8" },
    { src: "assets/img/Las Aventuras del Monito/Level3_1.jpg", to: "9" },
    { src: "assets/img/Las Aventuras del Monito/Level3_2.jpg", to: "10" },
    { src: "assets/img/Las Aventuras del Monito/Level3_3.jpg", to: "11" },
    { src: "assets/img/Las Aventuras del Monito/Level3_4.jpg", to: "12" },
    { src: "assets/img/Las Aventuras del Monito/Level3_5.jpg", to: "13" },
    { src: "assets/img/Las Aventuras del Monito/Level3_6.jpg", to: "14" },
    { src: "assets/img/Las Aventuras del Monito/Level3_7.jpg", to: "15" },
    { src: "assets/img/Las Aventuras del Monito/Level3_8.jpg", to: "16" },
    { src: "assets/img/Las Aventuras del Monito/Level3_9.jpg", to: "17" },
    { src: "assets/img/Las Aventuras del Monito/Level4_1.jpg", to: "18" },
    { src: "assets/img/Las Aventuras del Monito/Level4_2.jpg", to: "19" },
    { src: "assets/img/Las Aventuras del Monito/Level4_3.jpg", to: "20" },
    { src: "assets/img/Las Aventuras del Monito/Level4_4.jpg", to: "21" },
    { src: "assets/img/Las Aventuras del Monito/Level4_5.jpg", to: "22" },
    { src: "assets/img/Las Aventuras del Monito/Level4_6.jpg", to: "23" },
    { src: "assets/img/Las Aventuras del Monito/Level4_7.jpg", to: "24" },
    { src: "assets/img/Las Aventuras del Monito/Level4_8.jpg", to: "25" },
    { src: "assets/img/Las Aventuras del Monito/Level5_1.jpg", to: "26" },
    { src: "assets/img/Las Aventuras del Monito/Level5_2.jpg", to: "27" },
    { src: "assets/img/Las Aventuras del Monito/Level5_3.jpg", to: "28" },
    { src: "assets/img/Las Aventuras del Monito/Level5_4.jpg", to: "29" },
    { src: "assets/img/Las Aventuras del Monito/Level5_5.jpg", to: "30" },
    { src: "assets/img/Las Aventuras del Monito/Level5_6.jpg", to: "31" },
    { src: "assets/img/Las Aventuras del Monito/Level5_7.jpg", to: "32" },
    { src: "assets/img/Las Aventuras del Monito/Level5_8.jpg", to: "33" }
  ]
};
